name: Deploy on changes to server folder demo

on:
  push:
    branches:
      - main

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
        changes: ${{ steps.check_changes.outputs.changes }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Check for changes in server folder
        id: check_changes
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^apps/server/' && echo "changes=true" >> $GITHUB_OUTPUT || echo "changes=false" >> $GITHUB_OUTPUT

        
  deploy:
    runs-on: ubuntu-latest
    needs: check-changes
    if: needs.check-changes.outputs.changes == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy to production mock
        run: |
            echo "Deploying to production mock"