name: Deploy on changes to server folder demo

on:
  push:
    branches:
      - main

jobs:
  check-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for changes in server folder
        id: check_changes
        run: |
          echo "CHANGES=true" >> "$GITHUB_OUTPUT"
        
  deploy:
    runs-on: ubuntu-latest
    needs: check-changes
    if: ${{ needs.check_changes.outputs.CHANGES == 'true' }} == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to production mock
        run: |
            echo "Deploying to production mock"